project_details:
  name: "service-project-1"
  domain_prefix: "service-project-1-domain"
  folder_name: "dev-amber"
  apis:
    activate_apis:
      - "compute.googleapis.com"
      - "cloudkms.googleapis.com"
    disable_services_on_destroy: true
    disable_dependent_services: true
  shared_vpc:
    enable_shared_vpc_service_project: true
    svpc_host_project_id: "host-project-1"
    shared_vpc_network_name: "host-project-1-vpc"
service_account_details:
  service_accounts:
    host-project-sa:
      subnet_roles:
        - "roles/compute.networkUser"
subnet_details:
  subnets:
    subnet-01a:
      description: "simple subnet test"
      ip_cidr_range: "10.10.10.0/24"
      region: "us-central1"
      flow_logs_enable: "true"
      role: "ACTIVE"
      secondary_ip_range:
        - range_name: "subnet-01-secondary-01a"
          ip_cidr_range: "192.168.64.0/24"
        - range_name: "subnet-02-secondary-01a"
          ip_cidr_range: "192.169.65.0/24"
    subnet-01b:
      description: "simple subnet test2"
      ip_cidr_range: "10.20.10.0/24"
      region: "us-central1"
      flow_logs_enable: "true"
      role: "ACTIVE"
      secondary_ip_range:
        - range_name: "subnet-01-secondary-01b"
          ip_cidr_range: "192.170.64.0/24"
        - range_name: "subnet-02-secondary-01b"
          ip_cidr_range: "192.171.65.0/24"
notification_channels_details:
  notification_channels:
    email_notification_channel:
      type: "email"
      labels:
        email_address: "a1@abc.com"
      enabled: true
      description: "email_notification_channel"
      user_labels:
        key1: "value1"
        key2: "value2"
budget_details:
  billing_account: "1111-1111-1111-1111"
  budgets:
    budget-svc-prj-subnet-01:
      budget_filter:
        credit_types_treatment: "INCLUDE_ALL_CREDITS"   #Possible values are INCLUDE_ALL_CREDITS or EXCLUDE_ALL_CREDITS
        services: null
        calendar_period: null # Exactly one calender_period or custom_period must be provided. Possible values are MONTH, QUARTER, YEAR, CALENDAR_PERIOD_UNSPECIFIED
        custom_period: # Exactly one calender_period or custom_period must be provided.
          start_date:
            day: 01
            month: 01
            year: 2020
          end_date:
            day: 01
            month: 01
            year: 2022
      amount:
        specified_amount:
          currency_code: "US"
          currency_amount: 1000
      threshold_rules:
        alert_spent_percents: 0.5
        alert_spend_basis: "CURRENT_SPEND" # possible values are FORECASTED_SPEND or CURRENT_SPEND
      all_updates_rule:
        alert_pubsub_topic: "test_pubsub_topic"
        monitoring_notification_channels: []

